name: Wheel

on: [push, pull_request]

env:
  CIBW_BUILD: "cp3*"
  CIBW_BEFORE_ALL: bash {project}/build_openslide.sh
  CIBW_TEST_COMMAND: python -m unittest {project}/tests/test_base.py {project}/tests/test_deepzoom.py {project}/tests/test_openslide.py {project}/tests/test_imageslide.py

jobs:
  wheel:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: 3.7
    
    - name: Install cibuildwheel
      run: pip install cibuildwheel

    - name: Build wheel
      run: cibuildwheel .